app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: https://herokustage.herokuapp.com


backend:
  baseUrl: https://herokustage.herokuapp.com
  listen:
    port: 
      $env: PORT
  # database:
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    pluginDivisionMode: 'schema'
    connection:
      host: ${POSTGRESQL_HOST}
      port: ${POSTGRESQL_PORT}
      user: ${POSTGRESQL_USER}
      password: ${POSTGRESQL_PASSWORD}
      database: ${POSTGRESQL_DATABASE}
      # https://node-postgres.com/features/ssl
      # ssl: require # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
        #ca: # if you have a CA file and want to verify it you can uncomment this section
        #$file: <file-path>/ca/server.crt